# This is a pipeline for the AI4Devs project
name: AI4Devs Pipeline

on:
  pull_request:
    branches: 
      - 'main'
    types: [synchronize, opened, reopened, ready_for_review]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-backend:
    name: ğŸ§ª Tests
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ˜¼ Checkout
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: ğŸ”§ Install dependencies
      run: |
        cd backend
        npm ci

    - name: â›‘ï¸ Run backend tests
      run: |
        cd backend
        npm test
